#!/bin/bash

echo “Finding the PID of your Dock”
dockPid=$(ps -ax | awk '$4 == "/System/Library/CoreServices/Dock.app/Contents/MacOS/Dock" {print $1}')
echo $dockPid
echo "Killing..."
kill -9 $dockPid
echo "Done!"
